Implement POST sct-treasury/deposit
solid-world/solid-world-marketplace-backend pull request #107
Opened 2022-04-18 13:32 UTC by freitasgouvea

Implement POST `sct-treasury/deposit` endpoint:

- Add sct-treasury route
- Add sct-treasury controller
- Add sct-treasury/deposit validators
- Update swagger

Closed #101

2022-04-18 14:55 UTC, jeffprestes requested changes

2022-04-18 14:55 UTC, jeffprestes commented on app.js
> +app.use('/api/v1/sct-treasury', sctTreasury)
let's not use - or any other symbols in the api endpoints. It could create bad situations for client (bad url encoding).
```suggestion
app.use('/api/v1/scttreasury', sctTreasury)
```

2022-04-18 14:55 UTC, jeffprestes commented on swagger.json
> +      "name": "sct-treasury",
```suggestion
      "name": "scttreasury",
```

2022-04-18 14:55 UTC, jeffprestes commented on swagger.json
> +        "summary": "/api/v1/sct-treasury/deposit",
For the reasons explained at app.js , the 
```suggestion is
        "summary": "/api/v1/scttreasury/deposit",
```

2022-04-19 19:46 UTC, freitasgouvea commented
I will close this pull request brcause all changes implemented here was merged by PR #109

2022-04-19 19:46 UTC, closed without merging