Implement wallet signature authentication and remove offer and cron-jobs
solid-world/solid-world-marketplace-backend pull request #135
Opened 2022-06-14 18:18 UTC by freitasgouvea

This PR:

- implement new `POST/oauth2/wallet` endpoint 
- update `logcli_loginclient` model, migration and data seed
- update unit tests, `.env` variables and swagger docs 
- remove offer and cron-jobs implementations 
- remove unused database models

Closed #132 
Closed #129

2022-06-14 18:22 UTC, freitasgouvea commented
@raaha I would like to inform to you that this PR has two implementations that can have consequences on our CI/CD flow:

1.  New `.env` variables:

```
SECRET_KEY=''
AUTH_WALLET_MSG=''
```

2. The script `database/scripts/insert_sct_treasury_cron_job.js` was removed and we no longer need to run it when deploying a new version of the application

2022-06-14 18:27 UTC, lucasdcoutinh0 approved these changes

2022-06-14 20:46 UTC, jeffprestes requested changes

2022-06-14 20:46 UTC, jeffprestes commented on database/models/logcli_loginclient.js
> +    logcli_wallet_address: { type: DataTypes.STRING, allowNull: false },
I believe the field should accept null because a system might not have an Ethereum Address.

2022-06-14 20:46 UTC, jeffprestes commented on database/seeders/20220101000001-seed-logcli_loginclient.js
> +    return queryInterface.bulkInsert('logcli_loginclient', [
I believe the mock data must have data for marketplace frontend and backoffice. They can have role as system and as they are systems their wallet must be null.

2022-06-14 23:24 UTC, freitasgouvea commented on database/models/logcli_loginclient.js
> +    logcli_wallet_address: { type: DataTypes.STRING, allowNull: false },
Yes, I will change to accept null

2022-06-14 23:25 UTC, freitasgouvea commented on database/seeders/20220101000001-seed-logcli_loginclient.js
> +    return queryInterface.bulkInsert('logcli_loginclient', [
Great, I will create these two clients with system role

2022-06-15 12:29 UTC, jeffprestes approved these changes

2022-06-15 12:29 UTC, merged